#!/bin/bash

url=$1

echo "Starting archiving!"

youtube-dl $url \
--download-archive downloaded.txt \
-o "%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s" \
-f bestvideo[ext=mp4]+bestaudio[ext=m4a] \
--merge-output-format mp4 \
--add-metadata \
--write-thumbnail \
--write-description \
--write-info-json \
--write-annotations \
--all-subs

echo "Archiving done!"


